# 시간복잡도
- 빅 오메가
- 빅 세타
- 빅 오

코딩테스트에서는 빅 오를 기준으로 수행 시간을 계산하는 게 좋다.
여러 케이스를 통과해야만 하기 때문에, 테스트 케이스의 데이터가 긴 경우에 시간 초과가 될 수 있기 때문이다.

In [7]:
import random

cnt = 1
findNumber = random.randrange(1, 101) # 1~100 사이의 난수 생성

for i in range(1, 101) :
    if i == findNumber :
        print(i, '찾았다!')
        print(cnt, '번만에 찾았다!')
        break
    cnt += 1

41 찾았다!
41 번만에 찾았다!


# 슈도코드 작성
프로그램을 만드는 데 필요한 변수와 함수 등을 미리 작성해본다.
어떤 방식으로 코드를 짜야 할지 미리 그려보는 레이아웃 역할을 한다.

In [ ]:
# N 과목수 입력
# scoreList에 점수 저장
# maxScore에 scoreList의 최댓값 저장
# sumScore에 scroeList의 점수 합계 저장
# sumScore * 100 / maxScore / N
# 정수를 한 줄로 입력해서 띄어쓰기를 기준으로 배열 생성

# 슈도코드를 바탕으로 실제 코드 작성

In [5]:
n = int(input('과목 수: ')) # 입력받은 값을 정수형으로 저장
scoreList = list(map(int, input('점수 입력: ').split())) # 공백을 기준으로 데이터 입력받음
maxScore = max(scoreList)
sumScore = sum(scoreList)

print(sumScore * 100 / maxScore / n)

66.66666666666667


# 수정된 점수와 평균 점수를 각각의 줄에 출력
- 기존 점수를 수정해서 scoreList에 저장한다.

In [12]:
# n에 과목수 저장
# scoreList에 점수 저장
# maxScore에 scoreList의 최댓값 저장
# scoreList의 수정된 점수를 newScore에 저장
# newScore와 평균 점수 출력

n = int(input('과목 수: '))
scoreList = list(map(int, input('점수 입력: ').split()))
maxScore = max(scoreList)

print(scoreList) # 입력한 점수 출력

for i in range(n) :
    scoreList[i] = scoreList[i] * 100 / maxScore

sumScore = sum(scoreList) # 수정된 점수의 합계 저장

for i in range(n) : # 수정된 점수를 각각의 줄에 출력
    print(scoreList[i])
print(sumScore / n) # 수정된 점수의 평균 출력

[10, 20, 30]
33.333333333333336
66.66666666666667
100.0
66.66666666666667


In [8]:
suNo, quizNo = map(int, input('수강생 수, 퀴즈 수').split()) # 수강생 수와 퀴즈 수를 입력받음
nums = list(map(int, input('수강생 점수').split())) # 각 수강생의 점수를 입력받음
prefixSum = [0] # 누적합을 저장할 리스트
temp = 0 # 누적합을 저장할 변수

for i in nums :
    temp += i
    prefixSum.append(temp)

for i in range(quizNo) :
    s, e = map(int, input('시작점, 종료점').split()) # s: 시작점, e: 종료점
    print(prefixSum[e] - prefixSum[s - 1])

12
9
1


In [23]:
# 리스트의 행 개수 n, 질의의 개수 m 입력받기
# 이차원 리스트 A에 저장할 값 입력받기
# A의 구간합을 이차원 리스트 D에 저장
# for i in m : print()로 출력

sizeN, cntM = map(int, input('N, M').split())
A = [[0] * (sizeN + 1)]
D = [[0] * (sizeN + 1) for i in range(sizeN + 1)]

for i in range(sizeN) :
    A.append([0] + list(map(int, input().split())))


In [26]:
for i in range(1, sizeN + 1) :
    for j in range(1, sizeN + 1) :
        D[i][j] = D[i][j - 1] + D[i - 1][j] - D[i - 1][j - 1] + A[i][j]

In [27]:
for i in range(cntM) :
    x1, y1, x2, y2 = map(int, input().split())
    result = D[x2][y2] - D[x1 - 1][y2] - D[x2][y1 - 1] + D[x1 - 1][y1 - 1]
    print(result)

27
6
64


ValueError: not enough values to unpack (expected 4, got 0)

In [20]:
import numpy as np

print(np.array(A))
print()
print(np.array(D))

[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  5  6  7  8]
 [ 0  9 10 11 12]
 [ 0 13 14 15 16]]

[[  0   0   0   0   0]
 [  0   1   3   6  10]
 [  0   6  14  24  36]
 [  0  15  33  54  78]
 [  0  28  60  96 136]]
